backbone = dict(
    type='ResNet_SlowFast',
    pretrained='modelzoo://resnet50',
    depth=50,
    num_stages=4,
    # out_indices=[0,3],
    out_indices=[0,1,2,3],
    frozen_stages=-1,
    inflate_freq=(0, 0, 1, 1),
    inflate_style='3x1x1',
    conv1_kernel_t=1,
    conv1_stride_t=1,
    pool1_kernel_t=1,
    pool1_stride_t=1,
    with_cp=False,
    bn_eval=False,
    partial_bn=False,
    style='pytorch')

spatial_temporal_module = dict(
    type='SimpleSpatialTemporalModule',
    spatial_type='avg',
    temporal_size=8,
    spatial_size=7),
segmental_consensus = dict(
    type='SimpleConsensus',
    consensus_type='avg')
cls_head = dict(
    type='ClsHead',
    with_avg_pool=False,
    temporal_feature_size=1,
    spatial_feature_size=1,
    dropout_ratio=0.5,
    in_channels=2048,
    num_classes=400)